version: "3"

services:
  nodeosd:
    image: eoslaomao/eosio-elastic:1.5.x
    command: /opt/eosio/bin/nodeos --data-dir /opt/eosio/bin/data-dir --config-dir /opt/eosio/bin/config-dir --replay-blockchain
    volumes:
      - ./data:/opt/eosio/bin/data-dir
      - ./config:/opt/eosio/bin/config-dir
    cap_add:
      - IPC_LOCK
    stop_grace_period: 5m
